"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-03 15:37:33.912288
"""
from alembic import op
import sqlalchemy as sa
import app.models.types


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('icon', sa.String(length=40), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'name', name='uq_category_kind_name')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_kind'), ['kind'], unique=False)

    op.create_table('embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=12), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('vector', sa.JSON(), nullable=False),
    sa.Column('updated_at', app.models.types.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', name='uq_embedding_entity')
    )
    op.create_table('revoked_tokens',
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('expires_at', app.models.types.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    with op.batch_alter_table('revoked_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revoked_tokens_expires_at'), ['expires_at'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.models.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.types.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('short_desc', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('locality', sa.String(length=80), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('website', sa.String(length=300), nullable=True),
    sa.Column('instagram', sa.String(length=80), nullable=True),
    sa.Column('hours', sa.String(length=160), nullable=True),
    sa.Column('price_min', sa.BigInteger(), nullable=True),
    sa.Column('price_max', sa.BigInteger(), nullable=True),
    sa.Column('price_label', sa.String(length=120), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('images', sa.JSON(), nullable=False),
    sa.Column('cover_image', sa.String(length=500), nullable=True),
    sa.Column('verification', sa.String(length=12), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('is_sample', sa.Boolean(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('search_text', sa.Text(), nullable=False),
    sa.Column('created_at', app.models.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.create_index('ix_business_visible', ['status', 'category', 'city'], unique=False)
        batch_op.create_index(batch_op.f('ix_businesses_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_businesses_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_businesses_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_businesses_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_businesses_status'), ['status'], unique=False)

    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=12), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('created_at', app.models.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'entity_type', 'entity_id', name='uq_favorite')
    )
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favorites_user_id'), ['user_id'], unique=False)

    op.create_table('inquiries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.Column('target_type', sa.String(length=12), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('target_title', sa.String(length=200), nullable=False),
    sa.Column('sender_name', sa.String(length=120), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('contact_method', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('reply_text', sa.Text(), nullable=True),
    sa.Column('replied_at', app.models.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.models.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inquiries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inquiries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inquiries_receiver_id'), ['receiver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inquiries_sender_id'), ['sender_id'], unique=False)
        batch_op.create_index('ix_inquiry_target', ['target_type', 'target_id'], unique=False)

    op.create_table('marketplace_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.Column('negotiable', sa.Boolean(), nullable=False),
    sa.Column('condition', sa.String(length=12), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('locality', sa.String(length=80), nullable=True),
    sa.Column('images', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('is_sample', sa.Boolean(), nullable=False),
    sa.Column('search_text', sa.Text(), nullable=False),
    sa.Column('created_at', app.models.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('marketplace_items', schema=None) as batch_op:
        batch_op.create_index('ix_market_visible', ['status', 'category', 'city'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketplace_items_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketplace_items_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketplace_items_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketplace_items_price'), ['price'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketplace_items_seller_id'), ['seller_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketplace_items_status'), ['status'], unique=False)

    op.create_table('mentor_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('headline', sa.String(length=160), nullable=False),
    sa.Column('expertise', sa.JSON(), nullable=False),
    sa.Column('education', sa.String(length=200), nullable=True),
    sa.Column('format', sa.String(length=80), nullable=True),
    sa.Column('availability', sa.String(length=120), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('is_sample', sa.Boolean(), nullable=False),
    sa.Column('search_text', sa.Text(), nullable=False),
    sa.Column('created_at', app.models.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('mentor_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mentor_profiles_status'), ['status'], unique=False)

    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', app.models.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('used_at', app.models.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.models.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('listing_type', sa.String(length=12), nullable=False),
    sa.Column('property_type', sa.String(length=40), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.Column('price_period', sa.String(length=10), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('locality', sa.String(length=80), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('area_sqft', sa.Integer(), nullable=True),
    sa.Column('furnishing', sa.String(length=20), nullable=True),
    sa.Column('amenities', sa.JSON(), nullable=False),
    sa.Column('images', sa.JSON(), nullable=False),
    sa.Column('poster_type', sa.String(length=20), nullable=False),
    sa.Column('availability', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('is_sample', sa.Boolean(), nullable=False),
    sa.Column('search_text', sa.Text(), nullable=False),
    sa.Column('created_at', app.models.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_properties_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_price'), ['price'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_status'), ['status'], unique=False)
        batch_op.create_index('ix_property_visible', ['status', 'listing_type', 'city'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=12), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('entity_title', sa.String(length=200), nullable=False),
    sa.Column('reason', sa.String(length=120), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=14), nullable=False),
    sa.Column('created_at', app.models.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_status'), ['status'], unique=False)

    op.create_table('business_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('price_label', sa.String(length=80), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('business_services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_services_business_id'), ['business_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_services_business_id'))

    op.drop_table('business_services')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_status'))
        batch_op.drop_index(batch_op.f('ix_reports_created_at'))

    op.drop_table('reports')
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_index('ix_property_visible')
        batch_op.drop_index(batch_op.f('ix_properties_status'))
        batch_op.drop_index(batch_op.f('ix_properties_price'))
        batch_op.drop_index(batch_op.f('ix_properties_owner_id'))
        batch_op.drop_index(batch_op.f('ix_properties_created_at'))
        batch_op.drop_index(batch_op.f('ix_properties_city'))

    op.drop_table('properties')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_token_hash'))

    op.drop_table('password_reset_tokens')
    with op.batch_alter_table('mentor_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mentor_profiles_status'))

    op.drop_table('mentor_profiles')
    with op.batch_alter_table('marketplace_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marketplace_items_status'))
        batch_op.drop_index(batch_op.f('ix_marketplace_items_seller_id'))
        batch_op.drop_index(batch_op.f('ix_marketplace_items_price'))
        batch_op.drop_index(batch_op.f('ix_marketplace_items_created_at'))
        batch_op.drop_index(batch_op.f('ix_marketplace_items_city'))
        batch_op.drop_index(batch_op.f('ix_marketplace_items_category'))
        batch_op.drop_index('ix_market_visible')

    op.drop_table('marketplace_items')
    with op.batch_alter_table('inquiries', schema=None) as batch_op:
        batch_op.drop_index('ix_inquiry_target')
        batch_op.drop_index(batch_op.f('ix_inquiries_sender_id'))
        batch_op.drop_index(batch_op.f('ix_inquiries_receiver_id'))
        batch_op.drop_index(batch_op.f('ix_inquiries_created_at'))

    op.drop_table('inquiries')
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favorites_user_id'))

    op.drop_table('favorites')
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_businesses_status'))
        batch_op.drop_index(batch_op.f('ix_businesses_owner_id'))
        batch_op.drop_index(batch_op.f('ix_businesses_created_at'))
        batch_op.drop_index(batch_op.f('ix_businesses_city'))
        batch_op.drop_index(batch_op.f('ix_businesses_category'))
        batch_op.drop_index('ix_business_visible')

    op.drop_table('businesses')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('revoked_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revoked_tokens_expires_at'))

    op.drop_table('revoked_tokens')
    op.drop_table('embeddings')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_kind'))

    op.drop_table('categories')
    # ### end Alembic commands ###
